--Execute: 3

USE [master]
GO

/****** Object:  Audit [TomocAudit]    Script Date: 5/19/2025 8:59:42 PM ******/
CREATE SERVER AUDIT [TomocAudit]
TO FILE
(	FILEPATH = N'C:\SQLAudits\'
	,MAXSIZE = 5120 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE, AUDIT_GUID = 'a7444d6c-e380-4c03-ba3f-b36292145028')
ALTER SERVER AUDIT [TomocAudit] WITH (STATE = ON)
GO

USE [TomocDb]
GO

CREATE DATABASE AUDIT SPECIFICATION [PrincipalAudit]
--ALTER DATABASE AUDIT SPECIFICATION [PrincipalAudit]
FOR SERVER AUDIT [TomocAudit]
ADD (DELETE ON DATABASE::TomocDb BY public),
ADD (EXECUTE ON DATABASE::TomocDb BY public),
ADD (INSERT ON DATABASE::TomocDb BY public),
ADD (SELECT ON DATABASE::TomocDb BY public),
ADD (UPDATE ON DATABASE::TomocDb BY public)
WITH (STATE = OFF)
GO

USE [TomocDb]

GO

ALTER DATABASE AUDIT SPECIFICATION [PrincipalAudit]
ADD (DATABASE_OBJECT_ACCESS_GROUP),
ADD (DATABASE_OBJECT_CHANGE_GROUP),
ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
ADD (DATABASE_PERMISSION_CHANGE_GROUP),
ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP),
ADD (FAILED_DATABASE_AUTHENTICATION_GROUP),
ADD (SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP),
ADD (BACKUP_RESTORE_GROUP)
WITH (STATE = ON);
GO