USE [master]
ALTER DATABASE [TomocDb] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
BACKUP LOG [TomocDb] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\TomocDb_LogBackup_2025-05-27_07-16-56.bak' WITH NOFORMAT, NOINIT,  NAME = N'TomocDb_LogBackup_2025-05-27_07-16-56', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [TomocDb] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\TomocDb.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [TomocDb] SET MULTI_USER

GO

--Script de ejemplo para el documento
USE [master]
ALTER DATABASE [TomocDb] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
BACKUP LOG [TomocDb] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\TomocDb_LogBackup_2025-05-31_12-26-57.bak' WITH NOFORMAT, NOINIT,  NAME = N'TomocDb_LogBackup_2025-05-31_12-26-57', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [TomocDb] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\TomocDb.bak' WITH  FILE = 2,  NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 5
RESTORE LOG [TomocDb] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\TomocDb_LogBackup_2025-05-31_12-26-57.bak' WITH  NOUNLOAD,  STATS = 5,  STOPAT = N'2025-05-31T12:24:30'
ALTER DATABASE [TomocDb] SET MULTI_USER

GO